import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main}`}>
        <br></br>
        <div id="fullDisplay">
        <div id="leftSide">
        <Image src={'/images/X_logo.png'} alt="X logo" width={341.57} height={308.75}/>
        </div>
        <div id="rightSide">
          <div class="firstSection">
            <h1>Happening now</h1>
            <h2>Join Today.</h2>
          </div>
          <div class="secondSection">
            <button id="googleButton">Sign up with Google</button>
            <button id="appleButton">Sign up with Apple</button>
            <hr></hr>
            <button id="createAccount">Create account</button>
            <p>By signing up, you agree to the <span class="fakeLink">Terms of Service</span> and <span class="fakeLink">Privacy Policy</span>, including <span class="fakeLink">Cookie Use.</span></p>
          </div>
          <div class="thirdSection">
            <h3>Already have an account?</h3>
            <button id="signIn">Sign in</button>
          </div>
        </div>
        </div>
        <footer>
          <p>About</p>
          <p>Download the X app</p>
          <p>Help Center</p>
          <p>Terms of Service</p>
          <p>Privacy Policy</p>
          <p>Cookie Policy</p>
          <p>Accessibility</p>
          <p>Ads info</p>
          <p>Blog</p>
          <p>Status</p>
          <p>Careers</p>
          <p>Brand Resources</p>
          <p>Advertising</p>
          <p>Marketing</p>
          <p>X for Business</p>
          <p>Developers</p>
          <p>Directory</p>
          <p>Settings</p>
          <p>© 2024 X Corp.</p>
    </footer>
        
      </main>

    </>
  )
}
