import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import First from '@/components/FirstComponent/index'
import Second from '@/components/SecondComponent/index'
import Third from '@/components/ThirdComponent/index'
import Footer from '@/components/FooterComponent/index'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.fullDisplay}>
          <div className={styles.leftSide}>
            <Image src={'/images/X_logo.png'} alt="X logo" width={341.57} height={308.75} layout="responsive"/>
          </div>
          <div className={styles.rightSide}>
            <First/>
            <Second/>
            <Third/>
          </div>
        </div>
        <Footer/>
      </main>
    </>
  )
}
